### ISSUE TITLE
Smart Selects not initialised in load()'ed form

### ISSUE THREAD

**Issue by davmlaw** [jazzband/django-smart-selects#219]
## Checklist

- [X ] This issue is not about installing previous versions of django-smart-selects older than 1.2.8. I understand that previous versions are insecure and will not receive any support whatsoever.
- [X ] I have verified that that issue exists against the `master` branch of django-smart-selects.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] I have debugged the issue to the `smart_selects` app.
- [X ] I have reduced the issue to the simplest possible case.
- [ ] I have included all relevant sections of `models.py`, `forms.py`, and `views.py` with problems.
- [X ] I have used [GitHub Flavored Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/) to style all of my posted code.

## Steps to reproduce

1. Render a Django view with a Smart Select form via jQuery.load()

## Actual behavior

The Smart Selects are not initialised

## Expected behavior

The Smart Selects are initialised.

## Workaround

Copy/Paste initItem() function from bindfields.js, then call that for each .chained-fk class in the newly loaded form.

**Comment by blag** [comment]
Can you give me an example of how you are using `jQuery.load()` to render a view? I'm not familiar enough with Javascript or jQuery to understand what all you're doing without more context.

Can you also post the results in the Javascript console in your web browser's developer tools? Thanks!

**Comment by davmlaw** [comment]
Imagine you have a view: view_show_smart_selects that has a form with a smart select. This renders when you access it directly ie http://localhost:8000/myapp/view_show_smart_selects

If you have another view, view2 that consists of a div of ID "#mydiv" and javascript that calls $("#mydiv").load("{% url 'view_show_smart_selects' %}"); When the 1st view is loaded into the 2nd view it gives the javascript error:

    chainedfk is not defined

**Comment by manelclos** [comment]
@davmlaw this should be fixed in latest master version, can you please test?

**Comment by davmlaw** [comment]
Sorry, I use Django autocomplete light now, so can't easily test this. Feel free to close if you think it's fixed.

**Comment by manelclos** [comment]
ok, closing, thanks!
