### ISSUE TITLE
Empty ChainedManyToMany In Admin When Editing

### ISSUE THREAD

**Issue by jbnance** [jazzband/django-smart-selects#237]
You **MUST** use this template when reporting issues. Please make sure you follow the checklist and fill in all of the information sections below.

----------------

All versions of django-smart-selects prior to version 1.2.8 are vulnerable to an XSS attack as detailed in [issue 171](https://github.com/digi604/django-smart-selects/issues/171#issuecomment-276774103). As a result, all previous versions have been removed from PyPI to prevent users from installing insecure versions. All users are urged to upgrade as soon as possible.

## Checklist

<sup><sup>Put an `x` in the bracket when you have completed each task, like this: `[x]`</sup></sup>

- [x] This issue is not about installing previous versions of django-smart-selects older than 1.2.8. I understand that previous versions are insecure and will not receive any support whatsoever.
- [x] I have verified that that issue exists against the `master` branch of django-smart-selects.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have debugged the issue to the `smart_selects` app.
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included all relevant sections of `models.py`, `forms.py`, and `views.py` with problems.
- [x] I have used [GitHub Flavored Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/) to style all of my posted code.

This appears to be similar to issue 212 but I'm running "master" and still having the issue described below.

## Steps to reproduce
1. Create models with ChainedManyToMany field
2. Using Django admin, add "parent" records and "child" record (N:N populates as expected)
3. Edit "child" record in Django admin interface

## Actual behavior
N:N select box is empty (no options to select and existing selections do not appear)

## Expected behavior
Previously selected options appear selected.  Any remaining valid options appear as available to select.

The "horizontal" option has no effect (select box is empty regardless of horizontal being true or false).

My Django version is 1.11.6 (though I have experienced this issue throughout the 1.11.x series).

The following JavaScript files are loaded:

/myapp/admin/jsi18n/
/myapp/static/admin/js/core.js
/myapp/static/admin/js/vendor/jquery/jquery.min.js
/myapp/static/admin/js/jquery.init.js
/myapp/static/admin/js/admin/RelatedObjectLookups.js
/myapp/static/admin/js/actions.min.js
/myapp/static/admin/js/urlify.js
/myapp/static/admin/js/prepopulate.min.js
/myapp/static/admin/js/vendor/xregexp/xregexp.min.js
https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js
/myapp/static/smart-selects/admin/js/chainedm2m.js
/myapp/static/smart-selects/admin/js/bindfields.js
/myapp/static/admin/js/SelectBox.js
/myapp/static/admin/js/SelectFilter2.js
/myapp/static/smart-selects/admin/js/chainedfk.js

The JavaScript console in Chrome shows the following request being made:

https://example.com/myapp/chaining/filter/inventory/URL/biz_app/inventory/JBossDomain/web_urls/89/

When I hit that URL manually the following data is displayed:
```
[{"display": "http://customer1.example.com:80", "value": 299}, {"display": "http://customer2.example.com:8230", "value": 301}, {"display": "https://customer3.example.com:443", "value": 300}]
```

Relevant `admin.py`:
```
class JBossDomainAdmin(admin.ModelAdmin):
    model = JBossDomain
    list_display = ['master_fqdn', 'app_url', 'biz_app']
    list_select_related = True

admin.site.register(JBossDomain, JBossDomainAdmin)
```

Relevant `models.py` - JBossDomain.web_urls is the field specific to this report:
```
class BizApp(models.Model):
    class Meta:
        verbose_name = 'Business Application'
        verbose_name_plural = 'Business Applications'
        unique_together = ('biz_service', 'ba_name')

    # 1:n with Business Service
    biz_service = models.ForeignKey(
        BizService,
        on_delete=models.PROTECT,
        verbose_name='Business Service',
    )

    ba_name = models.CharField(
        'Business Application Name',
        max_length=64,
    )

    def __str__(self):
        return '{} : {}'.format(
            self.biz_service,
            self.ba_name,
        )


class URL(models.Model):
    class Meta:
        verbose_name = 'URL'
        verbose_name_plural = 'URLs'
        unique_together = (
            ('fwd_record', 'proto'),
            ('fwd_record', 'port'),
            ('fwd_record', 'proto', 'port'),
        )

    # 1:n with Business Application
    biz_app = models.ForeignKey(
        BizApp,
        on_delete=models.PROTECT,
        verbose_name='Business Application',
    )

    # 1:n with DNS record
    # This should always point at an A or CNAME
    fwd_record = ChainedForeignKey(
        DNSRecord,
        chained_field='biz_app',
        chained_model_field='biz_app',
        on_delete=models.PROTECT,
        verbose_name='DNS A/CNAME Record',
        limit_choices_to={'rtype__in': [DNSRecord.A, DNSRecord.CNAME]},
    )

    # Protocol options
    HTTP = 'HTTP'
    HTTPS = 'HTTPS'
    PROTO_CHOICES = (
        (HTTP, 'http'),
        (HTTPS, 'https'),
    )

    proto = models.CharField(
        'Protocol',
        max_length=5,
        choices=PROTO_CHOICES,
    )

    port = models.PositiveIntegerField(
        'TCP Port',
        validators=[MaxValueValidator(65535)],
    )

    is_https_redirector = models.BooleanField(
        'HTTPS Redirector?',
        default=False,
    )

    # 1:n with LTM virtual server
    ltm_vs = models.ForeignKey(
        LTMVirtualServer,
        on_delete=models.PROTECT,
        verbose_name='LTM Virtual Server',
        blank=True,
        null=True,
    )

    # 1:1 with Docker container
    # We want this to be a ChainedOneToOne but that doesn't exist
    container = models.OneToOneField(
        DockerContainer,
        on_delete=models.PROTECT,
        verbose_name='Docker Container',
        blank=True,
        null=True,
    )

    def __str__(self):
        return '{}://{}:{}'.format(
            dict(self.PROTO_CHOICES)[self.proto],
            self.fwd_record.dns_src,
            self.port,
        )


class JBossDomain(models.Model):
    class Meta:
        verbose_name = 'JBoss Domain'
        verbose_name_plural = 'JBoss Domains'

    # 1:n with Business Application
    biz_app = models.ForeignKey(
        BizApp,
        on_delete=models.PROTECT,
        verbose_name='Business Application',
    )

    master_fqdn = models.CharField(
        'Master FQDN',
        # Per RFC
        max_length=255,
        unique=True,
        validators=[validate_lower],
    )

    # n:n with URL
    # Only allow URLs from the parent (biz app)
    web_urls = ChainedManyToManyField(
        URL,
        horizontal=True,
        chained_field='biz_app',
        chained_model_field='biz_app',
        verbose_name='Web URLs',
        related_name='jbossdomains_web_urls',
    )

    # 1:n with URL
    # Only allow URLs from the parent (biz app)
    app_url = ChainedForeignKey(
        URL,
        chained_field='biz_app',
        chained_model_field='biz_app',
        on_delete=models.PROTECT,
        verbose_name='App URL',
        related_name='jbossdomains_app_url',
    )

    @property
    def console(self):
        "Returns the console URL."
        return 'http://{}:9990/console/App.html'.format(self.master_fqdn)

    def __str__(self):
        return self.master_fqdn
```

**Comment by jbnance** [comment]
I've discovered that, when editing a record that exhibits this issue, if you change the selection for the chained field then change it back to the original value the correct data loads (both options and previously selected components).  So it appears that the page/object is just missing an "onload"-type setting for the initial values.

**Comment by jbnance** [comment]
I have updated my `settings.py` to include:

```
USE_DJANGO_JQUERY = True
JQUERY_URL = False
```

...which simplified the jQuery `.js` files being loaded but has not changed the results.

**Comment by jbnance** [comment]
Here's what the console shows on initial load of the page (`web_urls` is not populated);

```
XHR finished loading: GET "https://example.com/myapp/chaining/filter/inventory/URL/biz_app/inventory/JBossDomain/app_url/89/".
(anonymous)            @ VM412:1
send                   @ jquery.min.js:4
ajax                   @ jquery.min.js:4
n.(anonymous function) @ jquery.min.js:4
getJSON                @ jquery.min.js:4
fill_field             @ chainedfk.js:46
init                   @ chainedfk.js:78
initItem               @ bindfields.js:12
(anonymous)            @ bindfields.js:26
each                   @ jquery.min.js:2
(anonymous)            @ bindfields.js:25
i                      @ jquery.min.js:2
fireWith               @ jquery.min.js:2
ready                  @ jquery.min.js:2
J                      @ jquery.min.js:2
```

If I select a different "parent" and then go back to the original here is the console message for the return (which correctly populates the data):

```
XHR finished loading: GET "https://example.com/myapp/chaining/filter/inventory/URL/biz_app/inventory/JBossDomain/app_url/89/".
(anonymous)               @ VM412:1
send                      @ jquery.min.js:4
ajax                      @ jquery.min.js:4
n.(anonymous function)    @ jquery.min.js:4
getJSON                   @ jquery.min.js:4
fill_field                @ chainedfk.js:46
(anonymous)               @ chainedfk.js:90
dispatch                  @ jquery.min.js:3
r.handle                  @ jquery.min.js:3
ListPicker._handleMouseUp @ about:blank:893
```

**Comment by jbnance** [comment]
@digi604 @blag sorry to summon you individually, but is there anything more I can do to help troubleshoot this issue?  It's very impacting to our group and I'm highly motivated to do what I can to help.

**Comment by blag** [comment]
I’m at work and on mobile, so I’m a little rushed (sorry), but...

I merged a few PRs into `master` recently, have you/can you try out that and see if that fixes your problem? I’ll dig into this later this week over the US holiday, if not before.

I do have time to review PRs and merge them in. If you can get me a PR that fixes this for you (and passes tests and doesn’t break anything else) I’ll look it over, merge it in, and cut a released to PyPI for you later this week.

Sorry I’m not more help, when I started maintaining this I didn’t have a job but now I do and my free time to replicate and fix issues has decreased drastically.

Thanks!

**Comment by jbnance** [comment]
@blag thank you for the info.  Totally understand about time and commitments.  I will re-test with the latest master to see if the issue persists.

Unfortunately my JavaScript skills are weak (and AJAX skills non-existent) and I'm fairly certain this is a a JS issue.  Maybe I can bribe @erozqba to take a look.  ;-)  I no longer think it is as simple as a missing "onload" given that the XHR fires when the page loads (even thought he boxes aren't populated).  Could be a rendering order issue or something... I'm guessing.

Happy T-day!

**Comment by jbnance** [comment]
@blag I have tested with latest master and unfortunately the problem still persists (chained M2M fields are not populated in the admin interface when you go to edit an existing record).

**Comment by erozqba** [comment]
@blag I will try to look into this when I find some free time...

**Comment by mfaulkner9294** [comment]
Any progress on this?  I'm seeing the same behavior...

**Comment by blag** [comment]
@mfaulkner9294 Unfortunately not. Can you give me any additional troubleshooting information? Maybe try the branch I referenced in [this comment](https://github.com/digi604/django-smart-selects/issues/253#issuecomment-377007803).

**Comment by crackjack** [comment]
@blag using the branch you mentioned solves other problems, I have also submitted a PR that solves this problem when adding new entry, but this still exists in both master and js-unlint

**Comment by crackjack** [comment]
The class `ChainedSelect` in widget.py does seem to return correct HTML
```

**Comment by crackjack** [comment]
This new [PR](https://github.com/digi604/django-smart-selects/pull/260) fixes it for me @blag

**Comment by mfaulkner9294** [comment]
Any chance a release is coming soon with some of these critical bug fixes included?

**Comment by diogosimao** [comment]
Well,
I followed several tips, changes and branches after reading many issues related to empty m2m and fk fields. **This one** helped me the most.
It _fixes_ but it won't fix everything.
_E.g.:_
Fields won't be empty no longer
![peek 2018-05-31 14-37](https://user-images.githubusercontent.com/8460840/40798242-eae1df6a-64e0-11e8-8905-4a2a777851be.gif)

But it won't be field after chosen and saved.
_E.g.:_
![peek 2018-05-31 14-38](https://user-images.githubusercontent.com/8460840/40798328-26bd1482-64e1-11e8-844d-43882d2253ce.gif)
![peek 2018-05-31 14-38-01](https://user-images.githubusercontent.com/8460840/40798332-2c01f1ba-64e1-11e8-95bf-3e131396d87f.gif)

**Comment by developer2806** [comment]
Hi Facing the same issue while editing the chained m2m field. It doesnot appear first while editing. 

But if you change the selection for the chained field then change it back to the original value the correct data loads
Any fixes for this please?

**Comment by smitkamal9** [comment]
Hi,
I used JS Lint brach (https://github.com/digi604/django-smart-selects/tree/js-unlinting-fixes) and it solved the issue for me. Hope it helps.

Reference : https://github.com/digi604/django-smart-selects/issues/258

**Comment by walleza** [comment]
I have been facing the same problem since last year, any idea about this?

**Comment by JoveCat** [comment]
Facing the same issue while editing. I'm using ChainedForeignKey. when add new, it works fine, but while editing, it shows empty value.
Any fixes for this please?

**Comment by contorasebastian** [comment]
> Facing the same issue while editing. I'm using ChainedForeignKey. when add new, it works fine, but while editing, it shows empty value.
> Any fixes for this please?

Can confirm this aswell, 3 level (country-state-city) will cause a problem on last level, i can see the value selected for 1 second and after it resets to empt, this happens only in edit

**Comment by manelclos** [comment]
can people on this issue check if this is still happening in the latest master version?

**Comment by roszczypalam** [comment]
@manelclos I can confirm that bug still occurs on newest master

**Comment by manelclos** [comment]
@roszczypalam can you please check the test app and describe how to reproduce?

**Comment by Lorac** [comment]
We have the same issue, with the foreign key I have tracked it down to this: 

1. Init function is called with `init_value=1`
2. Choose correctly the option
3. `$(chainfield).change(function () {` is called
4. but now the initial value is `start_value="1"`. It will not work when you `===` with the initial value of `1` because they are a different type.
5. It selects nothing.

**Comment by amd77** [comment]
I've tried this pull request #306 which replaces === with ==  and seems to work. 👏

**Comment by prodigel** [comment]
@amd77 I can confirm that the PR was made to fix the empty 3+ chains of smart selects bug.

**Comment by manelclos** [comment]
Version [1.5.8](https://pypi.org/project/django-smart-selects/1.5.8/) which includes #306 is out

**Comment by manelclos** [comment]
@jbnance can you please confirm version 1.5.8 fixes your problem?

**Comment by jbnance** [comment]
Sorry, but I had to remove Smart Selects from our code base.  No offense intended to anyone involved - it is a great idea and when it worked it was awesome - I just needed something with a more responsive community.

**Comment by manelclos** [comment]
@jbnance no problem, community projects have ups and downs. You are welcome back anytime.
