### ISSUE TITLE
RemovedInDjango21Warning

### ISSUE THREAD

**Issue by timthelion** [jazzband/django-smart-selects#278]
`RemovedInDjango21Warning: Add the `renderer` argument to the render() method of <class 'smart_selects.widgets.ChainedSelect'>. It will be mandatory in Django 2.1. [boundfield.py:36]`

Changes need to be made here:

https://github.com/digi604/django-smart-selects/blob/master/smart_selects/widgets.py#L217

And here:

https://github.com/digi604/django-smart-selects/blob/master/smart_selects/widgets.py#L83

Here is an example of how to make the change:

https://github.com/adilkhash/django-wysiwyg-redactor/commit/b2c4ca33909ced447f3c1ee9bd01dab14d3a5ac2

@PetrDlouhy

**Comment by manelclos** [comment]
Hi @timthelion, tried with latest 2.0 and did not see the warning. Tried with 2.1 and it worked. Can you please add more information to this issue?

**Comment by manelclos** [comment]
@timthelion this has been fixed in https://github.com/jazzband/django-smart-selects/commit/6c00a6b54aeabce771218c07006cca156b3b06e2
