### ISSUE TITLE
Django 3 issue importing six

### ISSUE THREAD

**Issue by ccsv** [jazzband/django-smart-selects#295]
----------------
Simple issue Django 3.0+ moved six out of  django.utils can we replace lines like

*  `from django.utils import six` to `import six` in `db_fields.py`
*  `from django.utils.six import iteritems` to  `from six import iteritems`  in `views.py`

Not sure if this solution causes any compatibility issues with previous versions.

## Steps to reproduce

1. Install django 3.0 and smart selects
2. Use a smart selects feature like ChainedManyToManyField
3. You will get Import errors

## Actual behavior
Error Example 1

```
  File "C:\Users\0\Envs\wsite\lib\site-packages\smart_selects\urls.py", line 1, in <module>
    from smart_selects import views
  File "C:\Users\0\Envs\wsite\lib\site-packages\smart_selects\views.py", line 5, in <module>
    from django.utils.six import iteritems
ModuleNotFoundError: No module named 'django.utils.six'
```

Error Example 2
```
File "C:\Users\0\Envs\wsite\lib\site-packages\smart_selects\urls.py", line 1, in <module>
    from smart_selects import views
  File "C:\Users\0\Envs\wsite\lib\site-packages\smart_selects\views.py", line 5, in <module>
    from django.utils.six import iteritems
ModuleNotFoundError: No module named 'django.utils.six'
```

## Expected behavior
Run like normal

**Comment by ccsv** [comment]
As mentioned above changing the import statements will fix the issue. But I am not sure if it will interfere with any other issues.

**Comment by manelclos** [comment]
@ccsv this was fixed here https://github.com/jazzband/django-smart-selects/commit/c1082d91265e1809ca44ee45a65da3d457896396

Thanks for reporting. Please reopen if necessary.
