### ISSUE TITLE
Support Django 3.1

### ISSUE THREAD

**Issue by d9pouces** [jazzband/django-smart-selects#308]
## Checklist

<sup><sup>Put an `x` in the bracket when you have completed each task, like this: `[x]`</sup></sup>

- [X] This issue is not about installing previous versions of django-smart-selects older than 1.2.8. I understand that previous versions are insecure and will not receive any support whatsoever.
- [X] I have verified that that issue exists against the `master` branch of django-smart-selects.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] I have debugged the issue to the `smart_selects` app.
- [X] I have reduced the issue to the simplest possible case.
- [X] I have included all relevant sections of `models.py`, `forms.py`, and `views.py` with problems.
- [X] I have used [GitHub Flavored Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/) to style all of my posted code.

## Steps to reproduce

1. Install Django 3.1
2. Try to install Django-smart-selects

## Actual behavior

Django-smart-selects requires Django < 3.1

## Expected behavior

Django-smart-selects works with Django 3.1
A few quick tests do not show any bug, and just replacing "Django < 3.1" by "Django < 3.2" seems to be sufficient.

**Comment by manelclos** [comment]
@d9pouces great! thanks to checking and taking the time to report it. Will you send a PR?

**Comment by manelclos** [comment]
Fixed in https://github.com/jazzband/django-smart-selects/pull/309

**Comment by mbucknell** [comment]
I just tried to install django-smart-selects from pypi using pip and it is still requiring Django < 3.1

**Comment by manelclos** [comment]
Version [1.5.9](https://pypi.org/project/django-smart-selects/1.5.9/) which includes #309 is out
