### ISSUE TITLE
not work on django admin list filter

### ISSUE THREAD

**Issue by eromoe** [jazzband/django-smart-selects#81]
Evn : django-suit, django 1.7 ,python 2.7
`django-smart-selects` works perfect in add form view but list view.

code:

```
class Location(models.Model):
    province = models.ForeignKey(Province)
    city = ChainedForeignKey(
        City,
        chained_field="province",
        chained_model_field="province",
        show_all=False,
        auto_choose=True
    )
    name = models.CharField(max_length=20,)
    priority = models.IntegerField(null=True, blank=True)


class LocationAdmin(admin.ModelAdmin):
    list_display = ('name',)
    search_fields = ('name',)
    list_filter = ('province', 'city')
```

**Comment by jimmykobe1171** [comment]
Hi, can you describe more detail which part not working? Or capture a screenshot to show the detail?

**Comment by eromoe** [comment]
![qq 20150612112610](https://cloud.githubusercontent.com/assets/3938751/8123133/9ae07670-10f6-11e5-88d3-6fd21f2f897a.png)

```
class LocationAdmin(admin.ModelAdmin):
    list_display = ('name',)
    search_fields = ('name',)
    list_filter = ('province', 'city')
```

`list_filter = ('province', 'city')  `   change `province select` would not smart change the content of `city select` .

**Comment by jimmykobe1171** [comment]
Ic, django-smart-select do not handle such case right now, it only behave right as a model field.

**Comment by zh-h** [comment]
Override SimpleListFilter implement this feature

**Comment by blag** [comment]
@zh-h I'm not too familiar with customizing the Django admin page. Can you go into more detail or submit a PR?

**Comment by zh-h** [comment]
@blag Look this https://stackoverflow.com/questions/7296136/django-admin-filters-cascading

**Comment by manelclos** [comment]
This is out of scope until someone decides to implement it. Closing.
